version: 0.2
phases:
  pre_build:
    commands:
      - echo Setting up JDK 21
      - sdk install java 21-open
      - sdk use java 21-open
      - echo Logging in to Amazon ECR....
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 585768173240.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=585768173240.dkr.ecr.us-east-1.amazonaws.com/ust/book-sr
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Jar file
      - mvn clean install
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing to repo
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - DOCKER_CONTAINER_NAME=book-sr
      - printf '[{"name":"%s","imageUri":"%s"}]' $DOCKER_CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo Printing imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
    - target/springboot-aws-deploy.jar
